// This file was auto-generated by ML.NET Model Builder.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.ML;
using ToyBox.ML.Model;

namespace ToyBox.ML.TaxiFarePrediction.Model
{
    public class ConsumeModel : ConsumeModelBase<ModelInput, ModelOutput>
    {
    }
}