// This file was auto-generated by ML.NET Model Builder.

using System;
using Microsoft.ML.Data;
using ToyBox.StdLib.Mvvm;

namespace ToyBox.ML.TaxiFarePrediction.Model
{
    public class ModelOutput : NotifyPropertyChanged
    {
        private float score;

        public float Score { get => score; set => OnPropertyChanged(ref score, value); }
    }
}